name: ui_challenge
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.0.0
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  barcode_widget: ^2.0.4
  intl: ^0.19.0
  dotted_line: ^3.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - lib/features/day_one/presentation/