import 'package:ui_challenge/features/day_one/data/models/travel_data_model.dart';

List<TravelDataModel> travelDataList = [
  TravelDataModel(
    startCity: 'Cairo',
    startCityAbbrev: 'EG-C',
    destinationCity: 'Aswan',
    destinationCityAbbrev: 'EG-ASN',
    flightNumber: 'MU5700',
    passengerName: 'Abdalla',
    seatNumber: '15A',
    date: DateTime.utc(2023,1,1,21,5,12),
    gate: '05',
  ),
  TravelDataModel(
    startCity: 'Suez',
    startCityAbbrev: 'EG-SUZ',
    destinationCity: 'Luxor',
    destinationCityAbbrev: 'EG-LX',
    flightNumber: 'NS1156',
    passengerName: 'Nasser',
    seatNumber: '55S',
    date: DateTime.utc(2023,1,8,15,12,55),
    gate: '05',
  ),
  TravelDataModel(
    startCity: 'Cairo',
    startCityAbbrev: 'EG-C',
    destinationCity: 'Aswan',
    destinationCityAbbrev: 'EG-ASN',
    flightNumber: 'MU5700',
    passengerName: 'Abdalla',
    seatNumber: '15A',
    date: DateTime.utc(2023,1,1,21,5,12),
    gate: '05',
  ),
  TravelDataModel(
    startCity: 'Cairo',
    startCityAbbrev: 'EG-C',
    destinationCity: 'Aswan',
    destinationCityAbbrev: 'EG-ASN',
    flightNumber: 'MU5700',
    passengerName: 'Abdalla',
    seatNumber: '15A',
    date: DateTime.utc(2023,1,8,15,12,55),
    gate: '05',
  ),
  TravelDataModel(
    startCity: 'Cairo',
    startCityAbbrev: 'EG-C',
    destinationCity: 'Aswan',
    destinationCityAbbrev: 'EG-ASN',
    flightNumber: 'MU5700',
    passengerName: 'Abdalla',
    seatNumber: '15A',
    date: DateTime.utc(2023,1,1,21,5,12),
    gate: '05',
  ),
];
